layout_spectrum: 0.3189823
typography_spectrum: 0.2444091
color:
  saturation: 0.03763441
  lightness: 0.5609319
  brandStrength: 0.3649629
  brandColors:
    - '#D1D1CF'
    - '#1A1819'
    - '#ABA299'
    - '#3F3220'
    - '#867764'
  rhythmicContrast: 0.9498208
name: Meh Designs
